# Generated by Django 4.1.5 on 2023-01-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_files_changed_values_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='changed_values_url',
        ),
        migrations.RemoveField(
            model_name='files',
            name='uniquevalues_one_url',
        ),
        migrations.RemoveField(
            model_name='files',
            name='uniquevalues_two_url',
        ),
        migrations.AddField(
            model_name='files',
            name='changed_values',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='files',
            name='uniquevalues_one',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='files',
            name='uniquevalues_two',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
